export const DEFAULT_QR_STYLE = {
    fgColor: '#000000',
    bgColor: '#ffffff',
    size: 256,
    quietZone: 16,
    ecLevel: 'M',
    qrStyle: 'squares',
    eyeRadius: 0,
    eyeColor: '',
    logoImage: '',
    logoWidth: 60,
    logoHeight: 60,
    logoOpacity: 1,
    logoPadding: 5,
    logoPaddingStyle: 'square',
    removeQrCodeBehindLogo: true,
    enableLinearGradient: false,
    linearGradient: ['#000000', '#000000'],
    gradientDirection: [0, 0, 170, 170],
    frameStyle: 'none',
    frameText: 'SCAN ME',
    frameColor: '#000000',
    frameTextColor: '#ffffff',
};

export const COLOR_PRESETS = [
    { name: 'Classic', fg: '#000000', bg: '#ffffff' },
    { name: 'Navy', fg: '#1e3a5f', bg: '#ffffff' },
    { name: 'Forest', fg: '#1a5c2e', bg: '#ffffff' },
    { name: 'Sunset', fg: '#d4380d', bg: '#fff7e6' },
    { name: 'Royal', fg: '#531dab', bg: '#f9f0ff' },
    { name: 'Cherry', fg: '#a8071a', bg: '#fff1f0' },
    { name: 'Ocean', fg: '#006d75', bg: '#e6fffb' },
    { name: 'Midnight', fg: '#d4a017', bg: '#1a1a2e' },
];

export const DOT_STYLES = [
    { value: 'squares', label: 'Square' },
    { value: 'dots', label: 'Dots' },
    { value: 'fluid', label: 'Fluid' },
];

export const FRAME_STYLES = [
    { value: 'none', label: 'No Frame' },
    { value: 'simple', label: 'Simple Border' },
    { value: 'rounded', label: 'Rounded' },
    { value: 'badge-bottom', label: 'Badge Bottom' },
    { value: 'badge-top', label: 'Badge Top' },
    { value: 'banner', label: 'Banner' },
    { value: 'ticket', label: 'Ticket' },
    { value: 'fancy', label: 'Fancy' },
    { value: 'bubble', label: 'Bubble' },
    { value: 'shadow-box', label: 'Shadow Box' },
    { value: 'gradient-border', label: 'Gradient' },
    { value: 'minimal-dots', label: 'Minimal Dots' },
    { value: 'label-left', label: 'Label Left' },
    { value: 'ribbon', label: 'Ribbon' },
];

export const LOGO_GALLERY = [
    { name: 'Facebook', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/facebook.svg', category: 'Social' },
    { name: 'Instagram', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/instagram.svg', category: 'Social' },
    { name: 'Twitter/X', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/x.svg', category: 'Social' },
    { name: 'LinkedIn', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/linkedin.svg', category: 'Social' },
    { name: 'YouTube', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/youtube.svg', category: 'Social' },
    { name: 'TikTok', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/tiktok.svg', category: 'Social' },
    { name: 'WhatsApp', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/whatsapp.svg', category: 'Social' },
    { name: 'Telegram', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/telegram.svg', category: 'Social' },
    { name: 'Snapchat', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/snapchat.svg', category: 'Social' },
    { name: 'Pinterest', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/pinterest.svg', category: 'Social' },
    { name: 'GitHub', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg', category: 'Tech' },
    { name: 'Google', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/google.svg', category: 'Tech' },
    { name: 'Apple', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/apple.svg', category: 'Tech' },
    { name: 'Amazon', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/amazon.svg', category: 'Tech' },
    { name: 'Spotify', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/spotify.svg', category: 'Media' },
    { name: 'Discord', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/discord.svg', category: 'Social' },
    { name: 'Slack', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/slack.svg', category: 'Tech' },
    { name: 'PayPal', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/paypal.svg', category: 'Finance' },
    { name: 'Stripe', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/stripe.svg', category: 'Finance' },
    { name: 'Shopify', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/shopify.svg', category: 'Tech' },
    { name: 'Wi-Fi', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/wifi.svg', category: 'Utility' },
    { name: 'Location', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/googlemaps.svg', category: 'Utility' },
    { name: 'Email', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/gmail.svg', category: 'Utility' },
    { name: 'Phone', url: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/phone.svg', category: 'Utility' },
];

export const DOWNLOAD_SIZES = [
    { value: 200, label: '200px' },
    { value: 500, label: '500px' },
    { value: 1000, label: '1000px' },
    { value: 2000, label: '2000px' },
];
