apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seq-lams

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - clickhouse.yaml
  - backend.yaml
  - gateway.yaml
  - frontend.yaml
  - ingress.yaml
