apiVersion: v1
kind: Secret
metadata:
  name: seq-lams-secrets
type: Opaque
stringData:
  APP_JWT_SECRET: ed/+2eQjpKKy53ktI+JTcQfq3GSM0gQC4jidSjyeE9F+Jhdik7MsNS4Ibd9XQ233
  POSTGRES_PASSWORD: local-postgres-password
  REDIS_PASSWORD: local-redis-password
  RABBITMQ_USERNAME: app-user
  RABBITMQ_PASSWORD: local-rabbit-password
  CLICKHOUSE_PASSWORD: local-clickhouse-password
